services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py load_data && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/backend.env
      - ./envs/postgres.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./api:/app
    networks:
      - postgres_network

  postgres:
    image: postgres:15.6-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  postgres_volume:

networks:
  postgres_network:
    driver: bridge
