openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/ip-tags-report/{ip}/:
    get:
      operationId: v1_ip_tags_report_retrieve
      parameters:
      - in: path
        name: ip
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/ip-tags/{ip}/:
    get:
      operationId: v1_ip_tags_retrieve
      parameters:
      - in: path
        name: ip
        schema:
          type: string
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/ip-tags/create/:
    post:
      operationId: v1_ip_tags_create_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IPTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/IPTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/IPTag'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPTag'
          description: ''
  /api/v1/ip-tags/delete/{id}/:
    delete:
      operationId: v1_ip_tags_delete_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/ip-tags/list/:
    get:
      operationId: v1_ip_tags_list_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedIPNetworkTagList'
          description: ''
  /api/v1/ip-tags/retrive/{id}/:
    get:
      operationId: v1_ip_tags_retrive_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/ip-tags/update/{id}/:
    put:
      operationId: v1_ip_tags_update_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IPTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/IPTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/IPTag'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPTag'
          description: ''
    patch:
      operationId: v1_ip_tags_update_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedIPTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedIPTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedIPTag'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPTag'
          description: ''
components:
  schemas:
    IPNetworkTag:
      type: object
      description: |-
        Serializer for IpTag model with IP and tags.

        :returns: IPTagSerializer
        :rtype: rest_framework.serializers.Serializer
      properties:
        id:
          type: integer
          readOnly: true
        ip_network:
          type: string
        tag:
          type: string
          maxLength: 16
      required:
      - id
      - ip_network
      - tag
    IPTag:
      type: object
      description: |-
        Serializer for tags from IpTag model.

        :returns: IPTagSerializer
        :rtype: rest_framework.serializers.Serializer
      properties:
        tag:
          type: string
          maxLength: 16
      required:
      - tag
    PaginatedIPNetworkTagList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/IPNetworkTag'
    PatchedIPTag:
      type: object
      description: |-
        Serializer for tags from IpTag model.

        :returns: IPTagSerializer
        :rtype: rest_framework.serializers.Serializer
      properties:
        tag:
          type: string
          maxLength: 16
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
